[build]
  command = "pnpm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "16"

[build.lifecycle]
  onBuild = "curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm && pnpm install"
